### ISSUE TITLE
Pdb errors

### ISSUE THREAD

**Issue by yisampi** [LarryJiang134/Image_manipulation_detection#7]
please have a look at blew errors when i run "python train.py",thanks very much.
...
speed: 1.673s / iter
iter: 30 / 40000, total loss: 0.681241
 >>> rpn_loss_cls: 0.105365
 >>> rpn_loss_box: 0.005859
 >>> loss_cls: 0.264825
 >>> loss_box: 0.305192
 
speed: 1.405s / iter
> /data/sam.yi/Image_manipulation_detection/lib/layer_utils/proposal_target_layer.py(139)_sample_rois()
-> keep_inds = np.append(fg_inds, bg_inds)
(Pdb) 
(Pdb) 
(Pdb) 
(Pdb) 
(Pdb)

**Comment by michaelyan-coupa** [comment]
How did you fix this?

**Comment by littleBuddhaa** [comment]
@yisampi  @michaelyan-coupa  how was this fixed ?

**Comment by XueTuo** [comment]
try..catch
